### ISSUE TITLE
Cannot have multiple response headers w/ same name

### ISSUE THREAD

**Issue by AlecHaring** [sleeyax/burp-awesome-tls#17]
If the response contains multiple cookies w/ the same name (such as `set-cookie`), only one is returned.

`Set` overwrites the header's value, if a header with that key already exists:
https://github.com/sleeyax/burp-awesome-tls/blob/08fce6f79867de4568c1abb4d9690a318ac16820/src-go/server/server.go#L52-L55

`Add` could be used instead, but maybe instead of looping through all the headers and copying them that way, it would be better to just copy the `Header` instance from `res` to `w`?

**Comment by sleeyax** [comment]
Good catch, thanks. We can't do something like  `res.Header.Write(w)` because that would write the headers to the body instead of actually setting the HTTP headers in the response. Or what did you have in mind to shorten this, exactly? Suggestions are welcome.

**Comment by sleeyax** [comment]
Replaced  `Set  with `Add`. Though if you have another approach as an improvement, let me know or create a PR to I'll include it in the next release.

**Comment by AlecHaring** [comment]
> Or what did you have in mind to shorten this, exactly?

I was thinking we could call `res.Header.Clone()` and then swap the instance of the `ResponseWriter` w/ the cloned `Header`, but it does not look like there's a clean way to do it

**Comment by AlecHaring** [comment]
It seems like even after your fix, this issue is still not fully fixed. `res.Header.Get(k)` only returns the first value of the given key. I'll open a PR with a fix

**Comment by sleeyax** [comment]
Closed in https://github.com/sleeyax/burp-awesome-tls/pull/18
