### ISSUE TITLE
Crashing Burp on  Ubuntu 22.04

### ISSUE THREAD

**Issue by AmmeySaini** [sleeyax/burp-awesome-tls#20]
After loading the module and sending an HTTP request to the listener it crashes the whole BURP.
Burp version: 2022.9.1(Professional)
Java 17
os: Ubuntu 22.04

**Comment by sleeyax** [comment]
Does this happen every time or are there any specific steps required to reproduce this?

**Comment by AmmeySaini** [comment]
Happens everytime i try to send a request to the listener

**Comment by AmmeySaini** [comment]
@sleeyax can you let me know what OS you tested the extension on?

**Comment by sleeyax** [comment]
Arch linux, java 17

**Comment by AmmeySaini** [comment]
I ran your go code directly and found this log while sending a request to the listener 
`http: TLS handshake error from 127.0.0.1:35150: tls: first record does not look like a TLS handshake`

**Comment by sleeyax** [comment]
What site are you visiting?

**Comment by AmmeySaini** [comment]
https://httpbin.org/ip "GET"

**Comment by Arhimason** [comment]
same

**Comment by sleeyax** [comment]
Hi @AmmeySaini are you still having this issue with [v1](https://github.com/sleeyax/burp-awesome-tls/releases/tag/v1.0.0)? Thanks in advance for letting me know.

**Comment by sleeyax** [comment]
Assuming this is fixed, reopen if you're still having issues with the latest release.

**Comment by AmmeySaini** [comment]
@sleeyax I did check this again with the latest version, I can confirm this error is still there
cloned your repo and ran it directly
 
![image](https://github.com/sleeyax/burp-awesome-tls/assets/65405363/e4372505-5322-48c0-aaf7-7454b44755a7)

**Comment by sleeyax** [comment]
Are you accessing the site over HTTPS? Plain HTTP might cause unexpected results.

**Comment by AmmeySaini** [comment]
yes the website is using HTTPS, trying to access reddit.com, and this error is not always there, it happens randomly (around 10% of the time)
