### ISSUE TITLE
Add "InsecureSkipVerify: true" to tls config (RoundTrip: x509: certificate name does not match input)

### ISSUE THREAD

**Issue by VovkoO** [sleeyax/burp-awesome-tls#22]
Hi, I have problems with tls on some sites: RoundTrip: x509: certificate name does not match input.
Can we add "InsecureSkipVerify: true" to tls config here? 
https://github.com/sleeyax/burp-awesome-tls/blob/main/src-go/server/roundtripper.go#L84

**Comment by vellrya** [comment]
> Awesome TLS error: x509: certificate is valid for *.domain.xyz, domain.xyz, not sub-domain.domain.xyz:443

Strange error (I don't know why "sub-domain" with dash is not covered by wildcard), but probably it's easier to just disable the checks, as OP pointed out.
To be clear, this error occurred when trying to proxy an http/2 request.
