### ISSUE TITLE
Requests not working

### ISSUE THREAD

**Issue by hackermondev** [sleeyax/burp-awesome-tls#23]
I added the extension and I configured it but requests are not going through. The requests just get stuck on loading. 

Here's my config:
![image](https://user-images.githubusercontent.com/60828015/222783133-559b3832-3c13-4e40-990b-c87b3b1afd95.png)

burp proxy config:
![image](https://user-images.githubusercontent.com/60828015/222783267-8e5ee1b3-d650-48fb-a7a1-d5e8f73d2b39.png)

output:
![image](https://user-images.githubusercontent.com/60828015/222783394-d39dc549-f89a-47ef-86f6-1063503671b9.png)

**Comment by hackermondev** [comment]
@sleeyax

**Comment by sleeyax** [comment]
Proxy listener address in burp and awesome TLS settings can't be the same. Change the listener address to e.g. '127.0.0.1:8081' in awesome TLS settings.

**Comment by hackermondev** [comment]
> Proxy listener address in burp and awesome TLS settings can't be the same. Change the listener address to e.g. '127.0.0.1:8081' in awesome TLS settings.
I already tried that and I get this:
![image](https://user-images.githubusercontent.com/60828015/222794073-7096116a-a4ef-44bf-9048-790409f83b3a.png)

**Comment by sleeyax** [comment]
Try restarting burp.

**Comment by sleeyax** [comment]
I'm assuming it was a misconfiguration on your end and my suggestion(s) worked.
