### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by surfaceflinger** [sleeyax/burp-awesome-tls#26]
i've been able to bypass cloudflare bot check using android 11 okhttp preset, the thing is - entire burpsuite crashes after few seconds.

log: https://gist.github.com/surfaceflinger/fc66507ebbcc46d46e2b9218c91ee253

**Comment by sleeyax** [comment]
Should be resolved in https://github.com/sleeyax/burp-awesome-tls/pull/27
