### ISSUE TITLE
What is the purpose of the listener address?

### ISSUE THREAD

**Issue by SummerSec** [sleeyax/burp-awesome-tls#28]
What is the purpose of the listener address?

**Comment by sleeyax** [comment]
It's the local address and port the local HTTPS server should listen on. You need to reload the extension if you change + save this setting. Read https://github.com/sleeyax/burp-awesome-tls#how-it-works for more information.

**Comment by SummerSec** [comment]
I understand that the default case configuration is functional, I don't know if I understand it correctly?

**Comment by sleeyax** [comment]
Usually the default listener is fine and works out of the box. But if the default port isn't free on your system you can change it there.
