### ISSUE TITLE
Support for M1 Macs 

### ISSUE THREAD

**Issue by infosec-au** [sleeyax/burp-awesome-tls#30]
Love this project, was wondering if you could publish builds for M1 Macs (ARM)? Appreciate the work.

**Comment by sleeyax** [comment]
Someone tried to create a [PR for it in the past](https://github.com/sleeyax/burp-awesome-tls/pull/14), but closed it for some reason. I would happily accept a new PR. I don't have a M1 mac to test the build myself.

**Comment by sleeyax** [comment]
Closed in: https://github.com/sleeyax/burp-awesome-tls/pull/39
