### ISSUE TITLE
Wechat mini program can not catch the packet, Repeater can not send

### ISSUE THREAD

**Issue by CaoaiLWT** [sleeyax/burp-awesome-tls#36]
There was an error when the plug-in was installed, and several attempts were inexplably successful, but the package of wechat mini programs could not be caught and the response could not be sent. It is suggested that the author try it in the new environment

**Comment by sleeyax** [comment]
Unfortunately I can't test this because I don't have access to wechat (the keep banning my account for no reason). So you'll have to try and fix this issue yourself. I'll happily accept a PR for this!

**Comment by sleeyax** [comment]
More info is needed. Reopen if you can provide a reproducable example. Or create a PR to resolve the issue yourself.
