### ISSUE TITLE
Awesome TLS error: create spec from client hello: FingerprintClientHello: record is not a handshake

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [sleeyax/burp-awesome-tls#37]
<img width="1422" alt="图片" src="https://github.com/sleeyax/burp-awesome-tls/assets/31725824/b242e3f7-5549-495b-b0fa-1a52bffee7bb">

**Comment by sleeyax** [comment]
Can you provide more info for me to be able to reproduce this issue?

**Comment by sleeyax** [comment]
More info is needed. Reopen when you can provide a reproducible example.
