### ISSUE TITLE
Does this plugin have specific requirements for Java versions and Burp versions? I'm experiencing crashes when installing both the fat version and the Windows x64 version of the release on Burp 2023.10.3.6 with Java 17.0.99.

### ISSUE THREAD

**Issue by Trisscute** [sleeyax/burp-awesome-tls#45]

**Comment by sleeyax** [comment]
No. It should work with default Burp installation. 

Another issue has recently been opened that sounds similar to your problem. Please follow up on this issue from top to bottom starting from this comment https://github.com/sleeyax/burp-awesome-tls/issues/41#issuecomment-1822887845 and comment there if a) you have the same issue and b) can provide more useful information to help us debug the issue further.
