### ISSUE TITLE
Awesome TLS error: create spec from client hello: FingerprintClientHello: unsupported extension 65037

### ISSUE THREAD

**Issue by P1a0z1** [sleeyax/burp-awesome-tls#50]
copy client hello record as hex stream and paste it into the field "Hex Client Hello"

![图片1](https://github.com/sleeyax/burp-awesome-tls/assets/40374872/c7855a3f-c3b3-493f-a1da-97b2b5099d25)

Awesome TLS error: create spec from client hello: FingerprintClientHello: unsupported extension 65037
![图片](https://github.com/sleeyax/burp-awesome-tls/assets/40374872/f0d21bd6-e594-42f4-89f1-7e59f55ea1e7)

**Comment by sleeyax** [comment]
ECH (Encrypted Client Hello) extension `65037` is currently not supported by UTLS and therefore unavailable to Awesome TLS. Please try a Chrome fingerprint from the list instead. 

https://github.com/refraction-networking/utls/issues/240
