### ISSUE TITLE
Self signed certificate and not working port

### ISSUE THREAD

**Issue by HerrLeStrate** [sleeyax/burp-awesome-tls#60]
Hello! I configured Awesome TLS like this:
![image](https://github.com/sleeyax/burp-awesome-tls/assets/26091132/70436be7-ba56-431b-8b92-d1682aca7584)
And in my browser i've set proxy settings like this:
![image](https://github.com/sleeyax/burp-awesome-tls/assets/26091132/26dbde95-1509-4381-8e36-b7ce2c2bfa08)

When i try to open google.com via firefox developer, im getting error: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT.
Then i installed ca.der from this plugin to Firefox's certificate storage, and i'm getting following error: MOZILLA_PKIX_ERROR_CA_CERT_USED_AS_END_ENTITY.

How to configure plugin to work? 

Windows 11 Pro (x64)
Burp Suite Professional 2023.12.1.2
JDK 18 
Using 1.2.0 fat version of plugin.

**Comment by sleeyax** [comment]
Looks like a problem with your burp and browser configuration. Does burp's embedded browser work with the extension enabled?

**Comment by HerrLeStrate** [comment]
Yes, burp's embedded browser works. But afaik it uses default burp's proxy port - 8080, not 8565 (which used in awesome tls plugin)

**Comment by sleeyax** [comment]
You need to configure your browser to 8080 as well. The listener address is only for internal use by the TLS proxy.
