### ISSUE TITLE
[WINDOWS] Burp Suite crashes on startup with burp-awesome-tls extension enabled

### ISSUE THREAD

**Issue by nabil-ak** [sleeyax/burp-awesome-tls#62]
### Description
When I enable the `burp-awesome-tls` extension, Burp Suite crashes on startup.

### Steps to Reproduce
1. Start Burp Suite.
2. Install and enable the `burp-awesome-tls` extension.
3. The Burp Suite crashes instantly

### Expected Behavior
Burp Suite should start normally with the `burp-awesome-tls` extension enabled.

### Actual Behavior
Burp Suite crashes immediately on startup when the `burp-awesome-tls` extension is enabled.

### Burp Suite Version
Burp Suite Community Edition v2024.1.1.6

### Extension Version
v1.2.0

### Java Version
Java 21

### Additional Information 

<details><summary>--diagnostics flag output</summary>
---------------------------------------------------------------------------------------------------------
SYSTEM PROPERTIES
---------------------------------------------------------------------------------------------------------
awt.dnd.drag.threshold           15
com.sun.net.ssl.requireCloseNotify false
file.encoding                    UTF-8
file.separator                   \
flatlaf.uiScale.enabled          false
java.class.path                  burpsuite_community.jar
java.class.version               65.0
java.home                        D:\Programme\Java
java.io.tmpdir                   C:\Users\Nabil\AppData\Local\Temp\
java.library.path                D:\Programme\Java\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Mullvad VPN\resources;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\Users\Nabil\AppData\Local\Programs\Python\Launcher\;C:\Users\Nabil\AppData\Local\Microsoft\WindowsApps;C:\Users\Nabil\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Nabil\go\bin;.
java.runtime.name                Java(TM) SE Runtime Environment
java.runtime.version             21.0.2+13-LTS-58
java.specification.name          Java Platform API Specification
java.specification.vendor        Oracle Corporation
java.specification.version       21
java.vendor                      Oracle Corporation
java.vendor.url                  https://java.oracle.com/
java.vendor.url.bug              https://bugreport.java.com/bugreport/
java.version                     21.0.2
java.version.date                2024-01-16
java.vm.compressedOopsMode       Zero based
java.vm.info                     mixed mode, sharing
java.vm.name                     Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name       Java Virtual Machine Specification
java.vm.specification.vendor     Oracle Corporation
java.vm.specification.version    21
java.vm.vendor                   Oracle Corporation
java.vm.version                  21.0.2+13-LTS-58
jdk.debug                        release
jdk.tls.allowUnsafeServerCertChange true
jdk.tls.maxCertificateChainLength 1337
native.encoding                  Cp1252
org.bouncycastle.jsse.client.dh.minimumPrimeBits 1024
org.bouncycastle.jsse.client.dh.unrestrictedGroups true
os.arch                          amd64
os.name                          Windows 10
os.version                       10.0
path.separator                   ;
stderr.encoding                  cp850
stdout.encoding                  cp850
sun.arch.data.model              64
sun.awt.enableExtraMouseButtons  true
sun.boot.library.path            D:\Programme\Java\bin
sun.cpu.endian                   little
sun.cpu.isalist                  amd64
sun.io.unicode.encoding          UnicodeLittle
sun.java.command                 burpsuite_community.jar --diagnostics
sun.java.launcher                SUN_STANDARD
sun.jnu.encoding                 Cp1252
sun.management.compiler          HotSpot 64-Bit Tiered Compilers
sun.os.patch.level
user.country                     DE
user.dir                         D:\Programme\BurpSuiteCommunity
user.home                        C:\Users\Nabil
user.language                    de
user.name                        Nabil
user.script
user.timezone                    Europe/Berlin
user.variant

---------------------------------------------------------------------------------------------------------
SYSTEM RESOURCES
---------------------------------------------------------------------------------------------------------
Number of processors             8
Total JVM memory                 108 MiB
Max JVM memory                   3,98 GiB
Free JVM memory                  66,09 MiB

Total physical memory            15,93 GiB
Free physical memory             8,67 GiB
Total swap                       22,18 GiB
Free swap                        10,45 GiB

---------------------------------------------------------------------------------------------------------
BURP PROPERTIES
---------------------------------------------------------------------------------------------------------
Burp Version                     2024.1.1.6
Build Number                     27682
Product Name                     Burp Suite Community Edition
Burp Browser                     [version=122.0.6261.112, installationPath=D:\Programme\BurpSuiteCommunity\burpbrowser\122.0.6261.112]
Code source                      D:\Programme\BurpSuiteCommunity\burpsuite_community.jar
Debug ID                         qdov1t0g9oecadiq8zvq:o3bq
JAR type                         Installer
currenttimemillis                1710591326552
nanotime                         73352300819000

</details>
---

Thank you for your assistance.

**Comment by sleeyax** [comment]
See https://github.com/sleeyax/burp-awesome-tls/issues/41

Can you try the suggested solution(s) from there?

**Comment by nabil-ak** [comment]
I reinstalled the Nvidia driver on Windows and it worked. thank you!

**Comment by sleeyax** [comment]
Glad it worked! Windows can be so weird sometimes.
