### ISSUE TITLE
ERR_Empty_response issue

### ISSUE THREAD

**Issue by sayaanalam** [sleeyax/burp-awesome-tls#75]
Hi ,

I have installed the awesome tls and was trying to set it up but could not get it worked. I have setup the proxy address as 127.0.0.1:8881 in my browser proxy and 127.0.0.1:8881 as listen address on awesome tls tab, I am getting ERR_Empty_Response on my browser whenever i try to browse anything. Please check screenshots attached

![Screenshot 2024-07-20 at 12 35 05 PM](https://github.com/user-attachments/assets/beaf0410-ae28-45e9-b150-300de6c64455)
![Screenshot 2024-07-20 at 12 35 12 PM](https://github.com/user-attachments/assets/85da4852-0a99-4382-8267-3161d64dc53f)
![Screenshot 2024-07-20 at 12 35 20 PM](https://github.com/user-attachments/assets/159debcd-ae53-4efa-ade4-8511c85c8717)

**Comment by sleeyax** [comment]
You need to connect your browser to the burp proxy port and address. The listener address is only used Internally (but configurable in case the default port is taken or if you need to configure it for an advanced use case)

**Comment by sleeyax** [comment]
Assuming this is solved. Reopen the issue or create a discussion if you have more questions.

**Comment by sayaanalam** [comment]
Hi , 

I have tested it using the steps advised by you but it does not seems to make different. For example , chatgpt.com does not work with burpsuite normally, when i used it with extension, it did not work and showed me same behaviour. Please let me know if it does work for you with burp ON.

Thanks

**Comment by sleeyax** [comment]
Hmm it's related to the cloudflare captcha that is served on that domain. I seem to get a strange bad request error response as well.

So you're right, something is wrong with the extension in the way it requests and submits the JS challenges from the cloudflare captcha. Please create a news issue for this.
